name: Latest Blogs
on:
  schedule:
    - cron: '14 15 * * 6,0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGS"
          committer_username: "automation.aashutosh.dev"
          committer_email: "automation@aashutosh.dev"
          commit_message: "Update with latest blogs"
          feed_list: "https://blog.aashutosh.dev/rss.xml,https://nibbles.dev/feed.xml"
          remove_duplicates: true

