name: Latest book list from a goodreads
on:
  schedule: # Run workflow automatically
    - cron: "14 15 15 * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "96351756"
          shelf: "currently-reading"
